# SwiftLint Configuration for iOS Vinyl Tracker

# Included paths
included:
  - VinylTracker_Clean/VinylTracker/VinylTracker
  - VinylTracker_Clean/VinylTracker/VinylTrackerTests

# Excluded paths
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - todo

# Opt-in rules
opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs
  - strict_fileprivate
  - unneeded_parentheses_in_closure_argument

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 200
  error: 300

file_length:
  warning: 400
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - URL

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "\\bprint\\("
    message: "Use proper logging instead of print statements"
    severity: warning
    
  no_force_unwrap_in_tests:
    name: "No Force Unwrap in Tests"
    regex: "!\\s*(?!nil)"
    included: ".*Tests\\.swift"
    message: "Avoid force unwrapping in tests, use XCTUnwrap instead"
    severity: warning
